#!/usr/bin/env python3
"""Regenerate the ADIF DXCC entity-name table for the ham-radio domain.

Parses the DXCC Entity Code enumeration out of the ADIF specification HTML
(https://www.adif.org/315/ADIF_315.htm, windows-1252) and writes
collector/internal/plugins/domains/hamradio/dxcc_gen.go. The section is
bounded by the Mode enumeration anchor; later enumerations in the spec reuse
small integers and must not leak in.

Usage: python tools/gen-dxcc.py [--input ADIF_315.htm]
"""
import argparse
import html
import io
import pathlib
import re
import sys
import urllib.request

SPEC_URL = "https://www.adif.org/315/ADIF_315.htm"
OUTPUT = pathlib.Path(__file__).resolve().parent.parent / \
    "collector/internal/plugins/domains/hamradio/dxcc_gen.go"

# Display overrides where the official entity name is unwieldy on a HUD row.
OVERRIDES = {
    230: "Germany",
    291: "United States",
    522: "Kosovo",
}


def title_case(name: str) -> str:
    if not any(c.islower() for c in name):
        small = {"of", "the", "and", "da", "de"}
        words = []
        for index, word in enumerate(name.title().split()):
            lower = word.lower()
            words.append(lower if index > 0 and lower in small else word)
        return " ".join(words)
    return name


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", help="local copy of ADIF_315.htm")
    args = parser.parse_args()
    if args.input:
        raw = pathlib.Path(args.input).read_bytes()
    else:
        raw = urllib.request.urlopen(SPEC_URL, timeout=60).read()
    spec = raw.decode("windows-1252")

    start = spec.find("Enumeration_DXCC_Entity_Code")
    end = spec.find("Mode_Enumeration", start)
    if start < 0 or end < 0:
        print("DXCC enumeration section not found", file=sys.stderr)
        return 1
    section = spec[start:end]

    entities = {}
    for row in re.findall(r"<tr[^>]*>(.*?)</tr>", section, re.S):
        cells = [html.unescape(re.sub(r"<[^>]+>", "", cell)).strip()
                 for cell in re.findall(r"<td[^>]*>(.*?)</td>", row, re.S)]
        if len(cells) >= 2 and cells[0].isdigit():
            code = int(cells[0])
            entities.setdefault(code, OVERRIDES.get(code, title_case(cells[1])))
    if len(entities) < 300:
        print(f"only {len(entities)} entities parsed; refusing", file=sys.stderr)
        return 1

    out = io.StringIO()
    out.write("// Code generated by tools/gen-dxcc.py from the ADIF 3.1.5\n")
    out.write("// specification (https://www.adif.org/315/ADIF_315.htm); DO NOT EDIT.\n")
    out.write("package hamradio\n\n")
    out.write("// dxccEntityNames maps ADIF DXCC entity codes (PSKReporter sa/ra)\n")
    out.write("// to display names. Includes deleted entities; they still appear in feeds.\n")
    out.write("var dxccEntityNames = map[int]string{\n")
    for code in sorted(entities):
        name = entities[code].replace('"', '\\"')
        out.write(f"\t{code}: \"{name}\",\n")
    out.write("}\n")
    OUTPUT.write_text(out.getvalue(), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT} ({len(entities)} entities)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
